// Auto-generated by boneyard-js. Run `npx boneyard-js build` to regenerate.
// This file registers skeleton bone definitions for all named <Skeleton> components.
// Until bones are generated, boneyard-js falls back to its built-in pulse animation.
