"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _exam_card_list from './exam-card-list.bones.json'
import _candidate_table from './candidate-table.bones.json'
import _exam_screen from './exam-screen.bones.json'
import _exam_completed from './exam-completed.bones.json'

registerBones({
  "exam-card-list": _exam_card_list,
  "candidate-table": _candidate_table,
  "exam-screen": _exam_screen,
  "exam-completed": _exam_completed,
})
